src/WebAppProject/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebAppProject.Models
{
  
    [Serializable]
    public class Product : IEquatable<Product>
    {
        #region Properties

        public Guid ProductId { get; set; }

        [Required]
        [MaxLength(255)]
        [Display(Name = "Product Name")]
        public string ProductName { get; set; }

        [Required]
        public string Category { get; set; }

        [MaxLength(10000)]
        [Display(Name = "Description")]
        public string ProductDescription { get; set; }

        [Required]
        [Display(Name = "Unit price")]
        //[RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Invalid price")]
        [DataType(DataType.Currency)]
        [Range(0.00, 10000.00)]
        public decimal ProductPrice { get; set; }

        public string ImagePath { get; set; }

        public string ThumbPath { get; set; }

        [Required]
        [Range(0, 1000)]
        public int Quantity { get; set; }

        [Required]
        [Range(0, 10)]
        public int PriorityView { get; set; }

        [Required]
        [Display(Name = "Product is unlimited")]
        public bool IsUnlimited { get; set; }
        

       
        #endregion


        #region Implementation

        public Product()
        {
        }


        public Product(ProductModel model)
        {
            ProductId = Guid.NewGuid();
            Quantity = model.Quantity;
            ProductName = model.ProductName;
            ProductPrice = model.ProductPrice;
            IsUnlimited = model.IsUnlimited;
            ProductDescription = model.ProductDescription;
            Category = model.Category;
            PriorityView = model.PriorityView;
        }

        public Product(Product product)
        {
            ProductId = product.ProductId;
            Quantity = product.Quantity;
            ProductName = product.ProductName;
            ProductPrice = product.ProductPrice;
            IsUnlimited = product.IsUnlimited;
            ProductDescription = product.ProductDescription;
            Category = product.Category;
            PriorityView = product.PriorityView;
        }

        public Product(string name, string description, decimal price, string imagePath, string thumbPath, int quantity, bool isUnlimited, string category, int priorityView)
        {
            ProductId = Guid.NewGuid();
            Quantity = quantity;
            ImagePath = imagePath;
            ThumbPath = thumbPath;
            ProductName = name;
            ProductPrice = price;
            IsUnlimited = isUnlimited;
            ProductDescription = description;
            Category = category;
            PriorityView = priorityView;

        }

       

        #endregion


        #region IEqutable implementation

        public bool Equals(Product other)
        {
            if (other != null)
            {
                return this.ProductId == other.ProductId;
            }
            return false;
        }

        #endregion
    }
}

src/WebAppProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppProject.Interfaces;
using WebAppProject.Logic;
using WebAppProject.Models;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;

namespace WebAppProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IWebAppRepository _webAppSqlRepository;

        public ProductController(IWebAppRepository webAppSqlRepository)
        {
            _webAppSqlRepository = webAppSqlRepository;
        }


        // GET: Product
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_webAppSqlRepository.GetAll());
        }

        

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult ProductList()
        {

            return View(_webAppSqlRepository.GetAll());
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public ActionResult Create(ProductModel model)
        {
            var imageTypes = new string[] {"image/gif", "image/jpeg", "image/png"};

            if (model.Image == null || model.Image.Length == 0)
            {
                ModelState.AddModelError("Image", "This field is required!");
            }
            else if (!imageTypes.Contains(model.Image.ContentType))
            {
                ModelState.AddModelError("Image", "Please coose either GIF, JPEG or PNG image!");
            }

            
            if (ModelState.IsValid)
            {
                var product = new Product(model);
                
                // Save image to folder
                var imageName = $"{DateTime.UtcNow:yyyyMMdd-HHmmssfff}";
                var extension = Path.GetExtension(model.Image.FileName).ToLower();
                using (var img = Image.FromStream(model.Image.OpenReadStream()))
                {
                   
                    product.ImagePath = $"{imageName}{extension}";
                    product.ThumbPath = $"Thumbs/{imageName}{extension}";

                    // Save Thumbnail size image 240 x 240
                    Picture.SaveToFolder(img, new Size(180, 180), $"./wwwroot/images/Thumbs/{imageName}{extension}");

                    // Save large image 800 x 800
                    Picture.SaveToFolder(img, new Size(800, 800), $"./wwwroot/images/{imageName}{extension}");

                }

                _webAppSqlRepository.AddProduct(product);

                return RedirectToAction("ProductList");
            }
            return View(model);
        }



        // GET: Product/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }

            var product = _webAppSqlRepository.GetProduct((Guid)id);
            if (product == null)
            {
                return new NotFoundResult();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public IActionResult Edit(Product model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _webAppSqlRepository.Update(model);
                }
                catch (Exception)
                {
                    return new BadRequestResult();
                }
                
                return RedirectToAction("ProductList");
            }
            return View(model);
        }



        // GET: Product/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _webAppSqlRepository.GetProduct((Guid)id);
            if (product == null)
            {
                return new NotFoundResult();
            }

            return View(product);
        }



        // GET: Product/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new NotFoundResult();
            }

            var product = _webAppSqlRepository.GetProduct((Guid)id);
            if (product == null)
            {
                return new NotFoundResult();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.ActionName("Delete")]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        { 
            if (!_webAppSqlRepository.RemoveProduct(id))
            {
                return new BadRequestResult();
            }

            return RedirectToAction("ProductList");
        }


        [AllowAnonymous]
        public IActionResult Clothes()
        {
            List<Product> filtered = _webAppSqlRepository.GetFiltered(p => p.Category == "Clothes");

            return View(filtered);
        }

        [AllowAnonymous]
        public IActionResult Gift()
        {
            List<Product> filtered = _webAppSqlRepository.GetFiltered(p => p.Category == "Gift");

            return View(filtered);
        }
    }


}

src/WebAppProject/Controllers/ShoppingCartController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebAppProject.Interfaces;
using WebAppProject.Models;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace WebAppProject.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class ShoppingCartController : Controller
    {
        private readonly IWebAppRepository _webAppSqlRepository;
        private readonly UserManager<ApplicationUser> _appUserManager;

        public ShoppingCartController(IWebAppRepository webAppSqlRepository, UserManager<ApplicationUser> appUserManager)
        {
            this._webAppSqlRepository = webAppSqlRepository;
            this._appUserManager = appUserManager;
        }



        // GET: ShoppingCart
        
        public async Task<ActionResult> Index()
        {
            var user = await GetCurrentUser();
            var me = _webAppSqlRepository.GetUser(user);
            if (me == null)
            {
                return new BadRequestResult();
            }
            
            ShoppingCart sc = _webAppSqlRepository.GetActiveCart(me);
            if (sc == null)
            {
                sc = new ShoppingCart(me);
                _webAppSqlRepository.AddCart(sc);
            }
            return View(_webAppSqlRepository.GetCartItems(me));
        }


        public async Task<IActionResult> AddToCart(Guid id)
        {
            if (_webAppSqlRepository.TakeProduct(id, 1))
            {
                var user = await GetCurrentUser();
                var me = _webAppSqlRepository.GetUser(user);
                if (me == null)
                {
                    return new BadRequestResult();
                }
                var prod = _webAppSqlRepository.GetProduct(id);
                _webAppSqlRepository.AddToCart(me, prod, 1);
               
            }
            return RedirectToAction("Index");
        }



        // POST: ShoppingCart/Delete/5
        //[Microsoft.AspNetCore.Mvc.HttpPost]
        //[Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id)
        {
            var user = await GetCurrentUser();
            var me = _webAppSqlRepository.GetUser(user);
            if (me == null)
            {
                return new BadRequestResult();
            }

            if (!_webAppSqlRepository.RemoveFromCart(me, id, 1, false))
            {
                return new BadRequestResult();
            }
            
            return RedirectToAction("Index");
        }


        public async Task<ActionResult> DeleteAll()
        {
            var user = await GetCurrentUser();
            var me = _webAppSqlRepository.GetUser(user);
            if (me == null)
            {
                return new BadRequestResult();
            }
            _webAppSqlRepository.EmptyCart(me);
         
            return RedirectToAction("Index");
        }


        private async Task<ApplicationUser> GetCurrentUser()
        {
            return await _appUserManager.GetUserAsync(HttpContext.User);
        }
    }
}

src/WebAppProject/Views/Product/Clothes.cshtml
@using WebAppProject.Models
@model ICollection<WebAppProject.Models.Product>


<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/home.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/css/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="css/pigendo_bootstrap.css"/>
</head>
<body>


    @{
        IEnumerator<Product> enumerator = Model.GetEnumerator();
        int i = 1;
        enumerator.MoveNext();
        var s = enumerator.Current;
        while (s != null)
        {
            <div class="section">
                <div class="container">
                    <div class="row">
                        @while (s != null)
                        {
                            <div class="col-md-3">
                                <img src="~/images/@s.ImagePath" class="center-block img-responsive img-rounded">
                                <h2>@s.ProductName</h2>
                                <p>
                                    @s.ProductDescription
                                </p>
                                @if (!@s.IsUnlimited && s.Quantity < 10)
                                {
                                    if (s.Quantity != 0)
                                    {
                                        if (s.Quantity == 1)
                                        {
                                            <h5 style="color: #32cd32 !important;">This is last product at stock. Hurry up!</h5>
                                        }
                                        else
                                        {
                                            <h5 style="color: #32cd32 !important;">Only @s.Quantity products at stock. Hurry up!</h5>
                                        }

                                    }
                                    else
                                    {
                                        <h5 style="color: #b22222 !important;">Coming soon!</h5>
                                    }
                                }
                                <h3> PRICE: @s.ProductPrice </h3>
                                <a asp-area="" asp-route-id="@s.ProductId" asp-controller="ShoppingCart" asp-action="AddToCart">Add to cart</a>
                            </div>
                            bool flag = !enumerator.MoveNext();
                            if (i++ % 4 == 0 || flag)
                            {
                                s = enumerator.Current;
                                break;
                            }
                            s = enumerator.Current;
                        }

                    </div>
                </div>
            </div>
        }

    }

</body>
</html>

src/WebAppProject/Views/Product/Create.cshtml
@using WebAppProject.Models
@model WebAppProject.Models.ProductModel


@{
    ViewData["Title"] = "Create";
}

<html>

<link href="css/pigendo_bootstrap.css"/>

<head>
    
    <h2>Create</h2>

</head>
<body>


<form method="post" asp-action="Create" asp-controller="Product" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" placeholder="Enter product name"/>
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" placeholder="Enter product price"/>
                <span asp-validation-for="ProductPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Category" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Category" class="form-control" placeholder="Enter category" />
                <span asp-validation-for="Category" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PriorityView" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PriorityView" />
                <label asp-for="PriorityView"></label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsUnlimited" />
                    <label asp-for="IsUnlimited"></label>
                </div>
            </div>
        </div>
       <div class="form-group">
            <label asp-for="Quantity" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Quantity" class="form-control" placeholder="Enter product quantity"/>
                <span asp-validation-for="Quantity" class="text-danger"/>
            </div>
       </div>
       <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ProductDescription" class="form-control" placeholder="Describe your product"></textarea>
                <span asp-validation-for="ProductDescription" class="text-danger" />

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input asp-for="Image" title="Upload a product picture" type="file"/>
                <span asp-validation-for="Image" class="text-danger"></span>
                <br/>
             </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success"/>
                <a asp-action="ProductList" class="btn btn-warning">Cancel</a>
            </div>
        </div>

    </div>
</form>

</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


</html>

src/WebAppProject/Views/Product/Delete.cshtml
@using Microsoft.AspNetCore.Server.Kestrel
@using WebAppProject.Models
@model WebAppProject.Models.Product

@{
    ViewData["Title"] = "Delete";
}
<style type="text/css">
</style>

<html>

<link href="css/pigendo_bootstrap.css" />
<head>
    
    <h2>Delete</h2>

</head>
<body>

<form asp-action="Delete" asp-controller="Product" method="post">
    <div class="form-horizontal">
        <h4>Product</h4>
        <h3 class="text-danger">Are you sure you want to delete this product?</h3>
        <hr />
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Category" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Category" class="form-control" placeholder="Enter category" disabled="disabled"/>
                <span asp-validation-for="Category" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PriorityView" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PriorityView" class="form-control" disabled="disabled"/>
            </div>
        </div>
        @if (Model.IsUnlimited)
        {
            <div class="form-group">
                <label asp-for="Quantity" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <mark class="input-group" aria-checked="True" disabled="disabled"/>Product is unlimited<mark/>
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <label asp-for="Quantity" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Quantity" class="form-control" disabled="disabled" />
                </div>
            </div>
        }
        <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ProductDescription" class="form-control" disabled="disabled"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/images/@Model.ThumbPath" alt="@Model.ProductName image" class="img-thumbnail" />
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-danger"/>
                <a asp-action="ProductList" class="btn btn-warning">Cancel</a>
            </div>
        </div>
    </div>
</form>

</body>
</html>

src/WebAppProject/Views/Product/Details.cshtml
@using WebAppProject.Models
@model WebAppProject.Models.Product

@{
    ViewData["Title"] = "Details";
}

<html>

<link href="css/pigendo_bootstrap.css" />

<head>

    <h2>Details</h2>

</head>

<body>

<form asp-action="Details" asp-controller="Product">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" disabled="disabled" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" disabled="disabled"/>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Category" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Category" class="form-control" placeholder="Enter category" disabled="disabled"/>
                <span asp-validation-for="Category" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PriorityView" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PriorityView" class="form-control" disabled="disabled" />
            </div>
        </div>
        @if (Model.IsUnlimited)
        {
            <div class="form-group">
                <label asp-for="Quantity" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <mark class="input-group" aria-checked="True" disabled="disabled" />Product is unlimited<mark />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <label asp-for="Quantity" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Quantity" class="form-control" disabled="disabled" />
                </div>
            </div>
        }
        <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ProductDescription" class="form-control" disabled="disabled"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/images/@Model.ThumbPath" alt="@Model.ProductName image" class="img-thumbnail"/>
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a asp-action="Edit" asp-route-id="@Model.ProductId" class="btn btn-primary">Edit</a>
                <a asp-action="ProductList" class="btn btn-warning">Cancel</a>
            </div>
        </div>
    </div>
</form>

</body>

</html>

src/WebAppProject/Views/Product/Edit.cshtml
@using WebAppProject.Models
@model WebAppProject.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<html>

<link href="css/pigendo_bootstrap.css" />

<head>
    
    <h2>Edit</h2>
</head>

<body>

<form asp-action="Edit" asp-controller="Product" method="post">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" asp-for="ImagePath" />
        <input type="hidden" asp-for="ThumbPath" />
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" placeholder="Enter product name" />
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" placeholder="Enter product price" />
                <span asp-validation-for="ProductPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Category" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Category" class="form-control" placeholder="Enter category" />
                <span asp-validation-for="Category" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PriorityView" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PriorityView" />
                <label asp-for="PriorityView"></label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsUnlimited" />
                    <label asp-for="IsUnlimited"></label>
                </div>
            </div>
        </div>
        @if (!Model.IsUnlimited)
        {
            <div class="form-group">
                <label asp-for="Quantity" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Quantity" class="form-control" placeholder="Enter product quantity" />
                    <span asp-validation-for="Quantity" class="text-danger" />
                </div>
            </div>
        }
        else
        {
            Model.Quantity = 0;
        }
        <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="ProductDescription" class="form-control" placeholder="Describe your product"></textarea>
                <span asp-validation-for="ProductDescription" class="text-danger" />

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/images/@Model.ThumbPath" alt="@Model.ProductName image" class="img-thumbnail"/>
                <br />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success"/>
                <a asp-action="ProductList" class="btn btn-warning">Cancel</a>
            </div>
        </div>
    </div>
</form>
        
   </body>    

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</html>

src/WebAppProject/Views/Product/ProductList.cshtml
@using WebAppProject.Models
@model IEnumerable<WebAppProject.Models.Product>
@{
    ViewData["Title"] = "Index";
}

<html>

<link href="css/pigendo_bootstrap.css" />

<head>

    <h2>Index</h2>

</head>
<body>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayName("Picture")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsUnlimited)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div>
                    <img src="~/images/@item.ThumbPath" height=100 width=100>
                </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsUnlimited)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Category)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>
</body>
</html>